### ISSUE TITLE
Frontend // Navigation Bar(Header) should be implemented 

### ISSUE THREAD

**Issue by Physicliar** [bounswe/2021SpringGroup8#162]
Navigation Bar and Header should be implemented at frontend side so people can easily navigate in application. This will also increase the user experience.

**Comment by aydinmustafacan** [comment]
I have added navigation bar component to desired page and it works as intended. It enables users to go between listing of communities and community itself. Related commit can be found: 521f332a33f01842c7da7eadba5d9aa8e425ce90 . It has been included in master branch's last version to clone from. Since the implementation is done this issue can now be closed.
