### ISSUE TITLE
Frontend // Data Type Creation For Community is Implemented Needs to be Revised

### ISSUE THREAD

**Issue by Physicliar** [bounswe/2021SpringGroup8#164]
According to the requirement "1.1.5.4", data type creation for community is implemented . Now it allows only 3 fields for data type but it will be enhanced. The implementations can be found in the commit efea3aec187da54eb15d3f1fa33fd61030375533. Please test and review it @aydinmustafacan 
Here is the details of the implementation:
1- Create post  and data type button is implemented 
2- Create data type page is implemented

Details of the commit can be found in the commit message efea3aec187da54eb15d3f1fa33fd61030375533.

**Comment by aydinmustafacan** [comment]
Data type creation is functional and working as intended without any bugs according to my tests. Buttons for create post and data type looks good and they are functional. Further enhancement in terms of design choices can be made in the future. Since implementation is successful and functional issue can be closed.
