### ISSUE TITLE
Sign up and login pages for mobile app

### ISSUE THREAD

**Issue by aydinmustafacan** [bounswe/2021SpringGroup8#96]
Sign up and login pages need development for mobile

**Comment by mmuhammetcavus** [comment]
I designed signup and login pages, but did not bind them to server yet. They look like this
![WhatsApp Image 2021-11-08 at 11 08 18 PM](https://user-images.githubusercontent.com/55928183/140897512-4da738d0-0ab0-474c-af44-38222a09c047.jpeg)
 
![WhatsApp Image 2021-11-08 at 11 08 18 PM (1)](https://user-images.githubusercontent.com/55928183/140897521-6074c3d9-2a27-4075-a5f8-ed27daccf442.jpeg)
Since we do not have a logo yet, I added some image as logo to see how the page look like. Of course it will be changed once we decided our logo.

**Comment by aydinmustafacan** [comment]
You dont have to bind it to a server yet, just push your code with gradle wrapper so that we can test it locally. Also, you might create an apk and share it too.  In order to provide complete isolation and reproducibility it would be better if you were to provide a dockerfile as well with necessary instructions.

**Comment by mmuhammetcavus** [comment]
You are absolutely right. I will look into that as soon as possible
